import { promises as fs } from 'fs'
import path from 'path'
import { env } from '../../config/env.js'
import { KnowledgeGraph } from '../graph/knowledge-graph.js'
import { getLLMClient } from '../ai/llm-client.js'

export class DocumentGenerator {
  private llmClient: ReturnType<typeof getLLMClient> | null = null

  constructor() {
    // Try to initialize LLM client if API keys are available
    try {
      if (env.OPENAI_API_KEY || env.ANTHROPIC_API_KEY) {
        this.llmClient = getLLMClient()
      }
    } catch (error) {
      console.warn('LLM client not available:', error)
    }
  }

  /**
   * Generate enhanced documentation with AI insights
   */
  async generateEnhanced(
    projectName: string,
    projectUrl: string,
    graph: KnowledgeGraph,
    screenshots?: string[]
  ): Promise<string> {
    const basicMarkdown = await this.generateMarkdown(projectName, projectUrl, graph)

    if (!this.llmClient) {
      return basicMarkdown
    }

    try {
      // Use LLM to enhance documentation
      const stats = graph.getStats()
      const pages = graph.findPages('')
      const workflows = graph.detectWorkflows()

      const pagesData = pages.map((p) => ({
        title: p.title,
        url: p.url,
      }))

      const enhancedContent = await this.llmClient.generateDocumentation(
        pagesData,
        workflows
      )

      // Combine basic and enhanced content
      return `${basicMarkdown}\n\n---\n\n## AI-Generated Insights\n\n${enhancedContent}`
    } catch (error) {
      console.error('Failed to generate enhanced docs:', error)
      return basicMarkdown
    }
  }
  /**
   * Generate Markdown documentation from knowledge graph
   */
  async generateMarkdown(
    projectName: string,
    projectUrl: string,
    graph: KnowledgeGraph
  ): Promise<string> {
    const stats = graph.getStats()
    const pages = graph.findPages('')
    const workflows = graph.detectWorkflows()

    let markdown = `# ${projectName} Documentation\n\n`
    markdown += `> Auto-generated documentation for ${projectUrl}\n\n`
    markdown += `---\n\n`

    // Table of contents
    markdown += `## Table of Contents\n\n`
    markdown += `- [Overview](#overview)\n`
    markdown += `- [Pages](#pages)\n`
    markdown += `- [Workflows](#workflows)\n`
    markdown += `- [Statistics](#statistics)\n\n`

    markdown += `---\n\n`

    // Overview
    markdown += `## Overview\n\n`
    markdown += `This application contains **${stats.pages} pages** with **${stats.elements} interactive elements**.\n\n`

    // Pages
    markdown += `## Pages\n\n`
    pages.forEach((page) => {
      markdown += `### ${page.title}\n\n`
      markdown += `- **URL**: ${page.url}\n`
      markdown += `- **Status**: ${page.httpStatus}\n`

      // Get elements on this page
      const elements = graph.getNeighbors(page.id, 'out')
      if (elements.length > 0) {
        markdown += `- **Elements**: ${elements.length}\n`
        elements.forEach((el: any) => {
          if (el.text) {
            markdown += `  - ${el.elementType}: "${el.text}"\n`
          }
        })
      }

      markdown += `\n`
    })

    // Workflows
    if (workflows.length > 0) {
      markdown += `## Workflows\n\n`
      workflows.forEach((workflow, idx) => {
        markdown += `### ${idx + 1}. ${workflow.name}\n\n`
        workflow.steps.forEach((step, stepIdx) => {
          const node = graph.getNode(step)
          if (node) {
            markdown += `${stepIdx + 1}. ${(node as any).title || (node as any).text || step}\n`
          }
        })
        markdown += `\n`
      })
    }

    // Statistics
    markdown += `## Statistics\n\n`
    markdown += `| Metric | Value |\n`
    markdown += `|--------|-------|\n`
    markdown += `| Total Pages | ${stats.pages} |\n`
    markdown += `| Total Elements | ${stats.elements} |\n`
    markdown += `| Total Edges | ${stats.edges} |\n`
    markdown += `| Detected Workflows | ${workflows.length} |\n\n`

    markdown += `---\n\n`
    markdown += `*Generated by Floww on ${new Date().toLocaleString()}*\n`

    return markdown
  }

  /**
   * Generate HTML documentation
   */
  async generateHTML(markdown: string): Promise<string> {
    // Simple markdown-to-HTML conversion
    // In production, use a proper markdown library
    let html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API Documentation</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; border-bottom: 2px solid #ecf0f1; padding-bottom: 5px; }
        h3 { color: #7f8c8d; }
        code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }
        pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
        table { border-collapse: collapse; width: 100%; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #3498db; color: white; }
        blockquote { border-left: 4px solid #3498db; padding-left: 15px; color: #7f8c8d; }
    </style>
</head>
<body>
${markdown.replace(/^# (.+)$/gm, '<h1>$1</h1>')
  .replace(/^## (.+)$/gm, '<h2>$1</h2>')
  .replace(/^### (.+)$/gm, '<h3>$1</h3>')
  .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
  .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
  .replace(/\*(.+?)\*/g, '<em>$1</em>')
  .replace(/^---$/gm, '<hr>')
  .replace(/\n/g, '<br>')}
</body>
</html>`

    return html
  }

  /**
   * Save document to disk
   */
  async save(
    content: string,
    projectId: string,
    filename: string
  ): Promise<string> {
    const docsDir = path.join(env.OUTPUT_PATH || './storage/output', 'documents', projectId)
    await fs.mkdir(docsDir, { recursive: true })

    const filePath = path.join(docsDir, filename)
    await fs.writeFile(filePath, content, 'utf-8')

    return filePath
  }

  /**
   * Translate documentation to another language
   */
  async translate(content: string, targetLanguage: string): Promise<string> {
    if (!this.llmClient) {
      throw new Error('LLM client not available for translation')
    }

    return await this.llmClient.translate(content, targetLanguage)
  }

  /**
   * Generate documentation from page analysis
   */
  async generateFromAnalysis(
    analysisResults: Array<any>,
    workflows: Array<any>
  ): Promise<string> {
    let markdown = `# Application Documentation\n\n`

    markdown += `## Pages\n\n`
    for (const result of analysisResults) {
      markdown += `### ${result.page_purpose}\n\n`
      
      if (result.target_users && result.target_users.length > 0) {
        markdown += `**Target Users:** ${result.target_users.join(', ')}\n\n`
      }

      if (result.steps && result.steps.length > 0) {
        markdown += `**Steps:**\n\n`
        result.steps.forEach((step: string, idx: number) => {
          markdown += `${idx + 1}. ${step}\n`
        })
        markdown += `\n`
      }

      if (result.elements && result.elements.length > 0) {
        markdown += `**Elements:**\n\n`
        result.elements.forEach((el: any) => {
          markdown += `- **${el.selector}**: ${el.description}\n`
          if (el.user_action) {
            markdown += `  - ${el.user_action}\n`
          }
        })
        markdown += `\n`
      }

      if (result.common_issues && result.common_issues.length > 0) {
        markdown += `**Common Issues:**\n\n`
        result.common_issues.forEach((issue: string) => {
          markdown += `- ${issue}\n`
        })
        markdown += `\n`
      }

      markdown += `---\n\n`
    }

    if (workflows.length > 0) {
      markdown += `## Workflows\n\n`
      workflows.forEach((workflow: any, idx: number) => {
        markdown += `### ${idx + 1}. ${workflow.name}\n\n`
        markdown += `${workflow.description}\n\n`
        
        if (workflow.steps && workflow.steps.length > 0) {
          markdown += `**Steps:**\n\n`
          workflow.steps.forEach((step: any, stepIdx: number) => {
            markdown += `${stepIdx + 1}. ${step.action} on ${step.page}\n`
          })
          markdown += `\n`
        }
        
        markdown += `---\n\n`
      })
    }

    return markdown
  }
}

export const documentGenerator = new DocumentGenerator()
